name: Build lists
run-name: Build lists
on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows:
      - Remove dead domains
      - Remove parked domains
      - Manually add domains
      - Retrieve domains
      - Validate domains
    types:
      - completed
permissions:
  contents: write

jobs:
  build-lists:
    # Do not run if workflow_run failed/cancelled (still allows workflow_dispatch and workflow_call)
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: build_list.sh
        run: bash functions/build_lists.sh
        env:
          BLOCKLIST_DESCRIPTION: ${{ vars.BLOCKLIST_DESCRIPTION }}

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: build lists"
          git push -q
